### ISSUE TITLE
Schedule window cannot be scrolled.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#101]
Device: iTouch

![image](https://cloud.githubusercontent.com/assets/12791909/8665719/c7b2525e-2a19-11e5-8038-1d9fdc36afd2.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

It seems that we have updated all the devices and browsers here, and it seems that it is working fine on our end, although we don't have an itouch here, but heres what we got on our chrome emulator.
see attached screenshot [  
![ipodtouch-emulator](https://cloud.githubusercontent.com/assets/11186331/8717063/10e39b66-2bca-11e5-882b-7c9dd910a16e.jpg)
]

will send this as fixed, will wait for your feedback

Thanks,
Christian

**Comment by ermatitan** [comment]
Hello Christian, 

I really can't see a scroll bar on the actual device.
