### ISSUE TITLE
Media: images not shown on the next pages of the gallery

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#105]
http://crossfit-frantic.stage.titanweb.com.au/media-test-1/

I have created a page exactly the same the the current media page. 
Images not shown after clicking on the other pages, just he caption.

![image](https://cloud.githubusercontent.com/assets/12791909/8666967/5e08b2dc-2a2b-11e5-8d11-6ece6adf0c9e.png)

**Comment by rexcebudigital** [comment]
Hi Erma,

Please see screenshot below to solve the issue. Thanks.
![welcome ripe inflatable packers ripe packers](https://cloud.githubusercontent.com/assets/11186391/8669028/8fde4ebc-2a43-11e5-8ff0-993ceb216d52.png)
