### ISSUE TITLE
ACF: Featured image is too large

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#106]
![image](https://cloud.githubusercontent.com/assets/12791909/8667087/f2465782-2a2c-11e5-8158-8f05c75e90ec.png)

**Comment by rexcebudigital** [comment]
Hi Erma, can you please give me a link on this issue? I have checked and can't find it. Thanks.

**Comment by ermatitan** [comment]
not fix

**Comment by rexcebudigital** [comment]
Hi Erma, I have checked it on my end and I don't see issue, I did not change anything for this issue yet.
If the issue is still visible on your end, Kindly please include steps on how to replicate the issue. Thanks..
