### ISSUE TITLE
Wods : Page not found error displays when trying to access created wods page.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#12]
Newly created and previously created wods page all displays a page not found error

Screenshot: Wods - 01
![wods - 01](https://cloud.githubusercontent.com/assets/12791909/8075649/5c0d0f80-0f75-11e5-8d0d-6132577024e0.jpg)

**Comment by ramoncebudigital** [comment]
no single page design, single page for custom post type is disabled.

**Comment by ermatitan** [comment]
Since the user/client can access the said page/post, this problem should be fix
