### ISSUE TITLE
IE : Testimonial page has visible rectangular box background.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#125]
![image](https://cloud.githubusercontent.com/assets/12791909/8869065/3c7b9f3c-3212-11e5-82d0-ec01d5da47c9.png)

**Comment by rexcebudigital** [comment]
Hi Erma, this issue is not visible on my end. Please kindly let me know if the issue still exist so we can find way to replicate it. Thank you for being patient.

**Comment by ermatitan** [comment]
Hello Rex, problem is not longer reproducible in my end after the testimonial page was fixed to 2 columns. Thanks
