### ISSUE TITLE
Homepage: Meet The Coaches - Coach name or featured image is unclickable or no link

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#18]
In order to view the a coach full details, coach name/featured image should be clickable and link to each own page/post or coaches page

![image](https://cloud.githubusercontent.com/assets/12791909/8075621/097c6dd8-0f75-11e5-89a0-615f0acf7b7e.png)

**Comment by ramoncebudigital** [comment]
I linked to coaches page, since we don't have a single page design for coaches.
