### ISSUE TITLE
Visible white line found on mobile homepage

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#28]
Screenshot: Home - 07

Device: Ipad Air ; Samsung Tab 3
![home - 07](https://cloud.githubusercontent.com/assets/12791909/8075516/b53c61ca-0f73-11e5-997f-4c4dd9558d0e.jpg)

**Comment by ramoncebudigital** [comment]
working on my end.
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/8224840/ae61d25c-15bf-11e5-9ec6-0a3c0239b734.png)

**Comment by ermatitan** [comment]
Not working on my end. Problem occurs on all our devices: IPAD Air, Samsung Tab, S3, S4, ITouch
