### ISSUE TITLE
Footer : Opera Only - Visible line found at the footer

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#41]
Screenshot : Footer -02

![image](https://cloud.githubusercontent.com/assets/12791909/8204017/3f6a5fe2-1518-11e5-9280-07ba3fddbd1e.png)

**Comment by ramoncebudigital** [comment]
Hi, can you please comment the link for this bug so I can trace it. Thanks

**Comment by ermatitan** [comment]
Sorry but I have uploaded a wrong screenshot before, so i added a new one but it seems that I could not recreate the bug anymore, due to the "Meet The Coaches"  changes its size and background

**Comment by genesiscebudigital** [comment]
it is ok in my end. , please update your opera

**Comment by bernardtitan** [comment]
No fix: design issue
