### ISSUE TITLE
Home: Banner tagline text redundancy and clippings observed in different browser when minimized.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#42]
Screenshot : Home - 11
![home - 11](https://cloud.githubusercontent.com/assets/12791909/8075432/f12ff1ac-0f72-11e5-9988-1c941b7f12c7.jpg)

**Comment by ermatitan** [comment]
The clippings and the redundancy of text still occurs when minimize

**Comment by ermatitan** [comment]
Problem still occurs in all our mobile devices

**Comment by ermatitan** [comment]
Problem still occurs in all our mobile devices

**Comment by genesiscebudigital** [comment]
please provide updated screenshot. , don't have device here

**Comment by ermatitan** [comment]
Correct Banner Static Text : BOOK YOUR FREE CROSSFIT INTRODUCTION TODAY

Problem Occurs on the following Devices: Ipad Air, Samsung Tab3, ITouch, Samsung S3 and S4


Mobile Devices Screenshots:

IPAD Air:
![image](https://cloud.githubusercontent.com/assets/12791909/8422663/36f78562-1f11-11e5-8899-44a1edfd1e79.png)

IPOD
![image](https://cloud.githubusercontent.com/assets/12791909/8422749/5d3d8388-1f12-11e5-82bf-afd78a586ea7.png)

SAMSUNG TAB
![image](https://cloud.githubusercontent.com/assets/12791909/8422781/af04848c-1f12-11e5-8883-414aa17730d7.png)

**Comment by ermatitan** [comment]
Problem still reproducible in our end.  

Please also fix the type error "You" to "Your"

**Comment by ermatitan** [comment]
Not fix on the following

Desktop (Firefox/Chrome/IE/Opera) - Text Displayed was only "Book Your Free Croosfit Introduction"

IPAD Air - Landscape Layout - Tex displayed was only "Book Your Free Crossfit"

Samsung Tab - Landscape Layout - Text Displayed was only "Book Your Free Crossfit"

**Comment by ermatitan** [comment]
not fix on Samsung galaxy tab 3 landscape view ( "Today" text is still missing)
