### ISSUE TITLE
Media : Image description no longer displayed after deleting the gallery and then adding it back

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#50]
Is there a specific setting in which the image description will be displayed in the page just like the PSD design?

**Comment by ramoncebudigital** [comment]
follow these steps:
Manage galleries > (select a gallery) > Alt & Title Text / Description

adding a gallery in the page:
![screenshot_2](https://cloud.githubusercontent.com/assets/11186436/8228219/b5d650f6-15df-11e5-94ac-83f4b5140808.png)
