### ISSUE TITLE
Pages with parent page doesn't have breadcrumbs

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#55]
Coaches, Philosophy and About CFF has a parent page of Who We Are page but pages doesn't have breadcrumbs.

FAQ and Testimonial has a parent page of Get Started. FAQ has breadcrumbs but Testimonial page doesn't have. 

Questions: When do breadcrumbs display on page?

**Comment by ramoncebudigital** [comment]
This will depends on the designs.
