### ISSUE TITLE
The black background on Main and Play video are cut

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#68]

**Comment by genesiscebudigital** [comment]
please provide screenshot

**Comment by ermatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12791909/8298116/0b810e78-1997-11e5-82a8-f16c2bcc976f.png)

**Comment by genesiscebudigital** [comment]
the psd design is 640px width . , there is no PSD design above 640px and below 1200px;
please check on the 640px width

**Comment by ermatitan** [comment]
The PSD Design is the Mobile Design. Mobile devices and changing the browser's width should meet the said design to be consistent. Able to recreate this bug in Opera, Chrome, Firefox browser as well as on mobile devices. 

The black background on Menu and Play Video should continue until the edge of each device to be consistent.

**Comment by ermatitan** [comment]
Device: Samsung Tab 3 / S3
![image](https://cloud.githubusercontent.com/assets/12791909/8346167/4061ad9c-1b2b-11e5-9d2d-f92b04dbad0f.png)

Device: IPAD
![image](https://cloud.githubusercontent.com/assets/12791909/8346182/6df7e406-1b2b-11e5-9788-4c47003e51ef.png)


Problem not fix...
