### ISSUE TITLE
Post : Formatting disappears when adding text with bulleted or numbered list 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#7]
Add a new post (Sample Content - With Label.doc)

Screenshot: Post - 01
![post - 01](https://cloud.githubusercontent.com/assets/12791909/8075657/7b855c1e-0f75-11e5-84e7-019876bf82e4.jpg)

**Comment by ramoncebudigital** [comment]
No single page provided in the design specs.

**Comment by ermatitan** [comment]
Since the user/client can access the said page/post, this problem should be fix
