### ISSUE TITLE
FAQ and Testimonial featured image were stretched on Get Started page.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#74]
Device: Samsung Tab 3
![image](https://cloud.githubusercontent.com/assets/12791909/8348104/960e7796-1b41-11e5-8934-b390b53ef5de.png)

**Comment by genesiscebudigital** [comment]
I don't see featured image in the FAQ page . ,  please don't remove your testing . , it takes time

**Comment by ermatitan** [comment]
it's in this page: http://crossfit-frantic.stage.titanweb.com.au/get-started/
