### ISSUE TITLE
Homepage: Cut dark background on Book your free crossfit intro today.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Crossfit-Frantic#99]
Device: iTouch

![image](https://cloud.githubusercontent.com/assets/12791909/8665536/89eeaba4-2a17-11e5-99a8-9230a848dfc1.png)

**Comment by ermatitan** [comment]
Problem re-occur.
![image](https://cloud.githubusercontent.com/assets/12791909/8897800/0904c5f0-344e-11e5-9619-14d6f86deb05.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

This bug is invalid, since, we are using a background img on the body, causing this effect to occur, ive talk to bernard on this issue, and agreed to me about the bug, and this does not affect any functionality of the site :D, hopefully this bug can be closed.

Cheers,
Christian
